### ISSUE TITLE
don't change edit key when announcement is edited

### ISSUE THREAD

**Issue by nilesjohnson** [nilesjohnson/conference-list#36]
This appears to cause a great deal of confusion for some users.  Perhaps it is not worth the trouble.

**Comment by sethjohnson1** [comment]
The development branch almost does it already. Check line 10-13 on the View/Conferences/add.ctp (keeping in mind add/edit are unified view). Then just wrap the edit key business on Conference.php model around some sort of "if (!isset or !empty) and you should be good.
