### ISSUE TITLE
Clarify use of cookies

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#39]
Certain functionality appears to depend on the ability to set cookies; for instance, in my cookie-blocked browser the "apply subject filter" function throws this kind of error:

CSRF token is either expired or corrupted.

Error: The requested address '/conflistTWO/' was not found on this server.
Stack Trace

    [internal function] → ConferencesController->blackhole(string)
    ROOT/cakephp-2.4.5/lib/Cake/Controller/Component/SecurityComponent.php line 615 → call_user_func_array(array, array)
    ROOT/cakephp-2.4.5/lib/Cake/Controller/Component/SecurityComponent.php line 337 → SecurityComponent->_callback(ConferencesController, string, array)
    ROOT/cakephp-2.4.5/lib/Cake/Controller/Component/SecurityComponent.php line 242 → SecurityComponent->blackHole(ConferencesController, string)
    [internal function] → SecurityComponent->startup(ConferencesController)
    ROOT/cakephp-2.4.5/lib/Cake/Utility/ObjectCollection.php line 132 → call_user_func_array(array, array)
    [internal function] → ObjectCollection->trigger(CakeEvent)
    ROOT/cakephp-2.4.5/lib/Cake/Event/CakeEventManager.php line 247 → call_user_func(array, CakeEvent)
    ROOT/cakephp-2.4.5/lib/Cake/Controller/Controller.php line 675 → CakeEventManager->dispatch(CakeEvent)
    ROOT/cakephp-2.4.5/lib/Cake/Routing/Dispatcher.php line 182 → Controller->startupProcess()
    ROOT/cakephp-2.4.5/lib/Cake/Routing/Dispatcher.php line 160 → Dispatcher->_invoke(ConferencesController, CakeRequest, CakeResponse)
    APP/webroot/index.php line 113 → Dispatcher->dispatch(CakeRequest, CakeResponse)

A more helpful error message would be useful! (I can also trigger this error in a cookie-enabled browser by deleting the existing cookie, then trying to "apply subject filter" without reloading the page first.)

**Comment by nilesjohnson** [comment]
This looks like a bug in the cookie handling.  Will investigate.  Thanks!
