### ISSUE TITLE
Error in sublist display

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#40]
When I attempt to view a sublist, e.g., 

http://mathmeetings.net/ag-nt

I get at the bottom of page a table of errors, as in this screenshot:

![screenshot from 2015-12-24 12-24-02](https://cloud.githubusercontent.com/assets/2281037/11997756/cfd7d800-aa39-11e5-99c0-c9edb935eb2f.png)

**Comment by nilesjohnson** [comment]
This is some debugging output for development, but "Error" and "Affected" are actually two different columns.  So there are no errors here, just a print out of which rows/tables were touched.
