### ISSUE TITLE
Feature request: search box for host institution

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#41]
When filling out an entry for a new conference, it would be useful to have some sort of autocomplete for the "Host Institution" field. One perhaps easy-to-implement option would be to be able to search through the list of host institutions for existing entries in the database; that would quickly account for the most common repeats (e.g., MFO, CIRM, BIRS).

**Comment by nilesjohnson** [comment]
see #43

**Comment by kedlaya** [comment]
Related observation: if this were to be implemented, it would be useful to have the institution box occur higher on the form (e.g., just after the workshop title), and then use the preset entries to autopopulate the city/state and country fields.

**Comment by nilesjohnson** [comment]
> use the preset entries to autopopulate the city/state and country fields.

This is a great idea, but will require some updates to the database.  Recording my thoughts here until I actually get around to working on this (probably not soon).

* New table `Institutions`
* Set relationship `Conference hasOne Institution`
* On the New Announcement page, load json list of institutions for autocompletion (jquery; see idea on #43)
* Maybe need to limit the number of institutions?  Too many could make the page too slow(?)
* [This is the part I really don't know] Use some ajax to load the city and country fields?

**Comment by nilesjohnson** [comment]
merged to master
