### ISSUE TITLE
Drop-down menu for meeting type

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#43]
There aren't that many different meeting types. It might be easiest to have a drop-down menu with some of the most common options and an "other" option which would allow for a user-provided alternative.

Standard options might include: conference, school for graduate students, special session, software development workshop, collaborative research workshop, long-term research program. Based on what people fill into the "other" option, one might add more standard options later.

**Comment by nilesjohnson** [comment]
For future reference: this looks like a straightforward way to do this, since we already use jquery for the select boxes.  (Note:  select2 does not seem to support autocomplete in text boxes.)

http://jqueryui.com/autocomplete/
