### ISSUE TITLE
Add abbreviations USA, UK to country list

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#50]
The autocomplete in the country list is great, but it's not so helpful when trying to distinguish the rather common entries "United States of America" and "United Kingdom" for some rather less common entries, like "United Arab Emirates". Would it be possible to include "USA" and "UK" as entries in the autocomplete? These could either enter as is, or expand to the full names, whichever is easier/preferable.

**Comment by nilesjohnson** [comment]
The countries list is loaded from a separate project (https://github.com/mledoze/countries).  If we add our own, we will have to maintain our independent fork -- this is probably too much trouble for us.

Instead, we could implement some javascript that recognizes these abbreviations as alternate spellings.  After a brief skim of the [select2 examples](https://select2.github.io/examples.html), this seems doable.

In the meantime, here is a workaround:  the text matching works on any part of the name, not just the beginning, so you can use 'states' and 'kingdom', respectively, to specify the US and UK.

**Comment by kedlaya** [comment]
"states" also matches "United States Minor Outlying Islands" and "United States Virgin Islands". Fortunately, I was actually incorrect in the first post: the entry that appears is "United States" and not "United States of America", so it matches first among these.

**Comment by nilesjohnson** [comment]
On Fri, Jan 29, 2016 at 11:52 AM kedlaya <notifications@github.com> wrote:

> "states" also matches "United States Minor Outlying Islands" and "United
> States Virgin Islands". Fortunately, I was actually incorrect in the first
> post: the entry that appears is "United States" and not "United States of
> America", so it matches first among these.
>
Indeed, this is a happy accident (and underscores the need for a better
approach).
