### ISSUE TITLE
Front page should not by default show meetings in the past

### ISSUE THREAD

**Issue by juliusross1** [nilesjohnson/conference-list#58]
It would be more useful if the front page showed meetings that are happening in the future (or maybe include some in the very recent past).

**Comment by nilesjohnson** [comment]
Right now the list shows conferences who's *end* date is within the past
couple of weeks, or the future.  For long-running announcements, this gives
things where the start date is further in the past.  Is this the behavior
you're noticing, or is there a different issue?

I think the right way to handle this is to treat events that last longer
than, say, 1 month differently.  Either by putting them in a separate
section, or changing their style, or something else.

A related feature would be to change the style of currently​ running or
recently completed events, to make them visually distinct from future ones
-- this could make sense for both long and short term events.
