### ISSUE TITLE
duplicate entries cause additional repeat bug in main list

### ISSUE THREAD

**Issue by nilesjohnson** [nilesjohnson/conference-list#76]
When there are duplicate conference entries (e.g. conferences with id numbers 5, 6, 7 have exactly the same data) then there is an additional bug in the main list that causes them all to be repeated multiple times.  So, for example, one might see the following in the main list:

    5, 6, 7, 5, 6, 7, 5, 6, 7, etc.

They are repeated some number of times, and then the list continues on.

**Comment by nilesjohnson** [comment]
Maybe this is a bug in the find function for the main list, or in the grouping for multiple tags on the same conference.

**Comment by sethjohnson1** [comment]
The Paginator can cause unexpected results sometimes if the find function is wonky. One suggestion is use the query inspector and see what SQL statement is actually running.

- Seth

________________________________
